name: deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.16.9" #set here your version
  FLUTTER_CHANNEL: "stable" #set here your channel

jobs:
  flutter_test:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    name: Analyze
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          #1 - get depencies
          #2 - check if there are some warnings
          #3 - format all files at lib folder
      - run: |
          flutter clean 
          flutter pub get 
          flutter analyze 
  publish_ghPages:
    name: Publish GH Pages
    needs: [flutter_test] #only trigger this, if the test job runs ok...
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          flutter pub get
          flutter build web --release --base-href /panteon-cocktail-menu/
          cd build/web
          git init
          git config --global user.email cagkancaglayanel@gmail.com #change to your e-mail
          git config --global user.name Crosline #change to your user-name
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/Crosline/panteon-cocktail-menu.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
